### PR TITLE
Update jquery.emojiarea.js to hide Chrome Issues

### PR DESCRIPTION
**Pull request by prashantpandeyfun10**
Chrome doesnt render some emojis well...so to make this plugin full working we can just not render it and then delete this part of code when chrome figures this out!..

### CODE REVIEW

**Comment by Tlapi** [comment]
I dont see any problems with icons on Chrome...

**Comment by prashantpandeyfun10** [comment]
hi @Tlapi probably you are rendering the image...can you try with unicode? thanks

**Comment by TimBest** [comment]
These icons seem to be rendering on chrome just fine

**Comment by prashantpandeyfun10** [comment]
Why to close an unsolved issue. Certain emojis are still not rendered well and its an well known issue guys. @TimBest did you try looking into all the emojis. I guess not.

**Pull request closed without merging**
